app_register_jwt:
    path: /api/register_jwt
    controller: App\Controller\AuthController::register_jwt
    methods: POST

register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: POST

dashboard:
    path: /dashboard
    controller: App\Controller\UserLogdbController::index

api:
    path: /api
    controller: App\Controller\AuthController::api

api_login_check:
    path: /api/login_check

login_check:
    path:     /login_check
    methods:  [POST]

app_logout:
    path: /logout