register:
    path: /register
    controller: App\Controller\AuthController::register
    methods: POST

dashboard:
    path: /dashboard
    controller: App\Controller\UserLogdbController::index

api:
    path: /api
    controller: App\Controller\AuthController::api

login_check:
    path:     /login_check
    methods:  [POST]